.SILENT:

strength_potion: tarromin_potion limpwurt_root
	./mix bag/tarromin_potion bag/limpwurt_root
	echo "You add the limpwurt root to the tarromin potion and obtain strength potion."

tarromin_potion: tarromin vial_of_water
	./mix bag/tarromin bag/vial_of_water
	echo "You mix the tarromin in the vial of water and obtain tarromin potion."

tarromin:
	touch bag/tarromin
	echo "You pick up some tarromin off the ground somewhere."

vial_of_water:
	touch bag/vial_of_water
	echo "You buy a vial of water from the apothecary."

limpwurt_root:
	touch bag/limpwurt_root
	echo "You slay a few giants and one of them drops a limpwurt root."
