.SILENT:

strength_potion: tarromin_potion limpwurt_root
	./mix tarromin_potion limpwurt_root
	echo "You add the limpwurt root to the tarromin potion and obtain strength potion."

tarromin_potion: tarromin vial_of_water
	./mix tarromin vial_of_water
	echo "You mix the tarromin in the vial of water and obtain tarromin potion."

tarromin:
	touch tarromin
	echo "You pick up some tarromin off the ground somewhere."

vial_of_water:
	touch vial_of_water
	echo "You buy a vial of water from the apothecary."

limpwurt_root:
	touch limpwurt_root
	echo "You slay a few giants and one of them drops a limpwurt root."
